spring.application.name=student-spring-boot
spring.datasource.url=jdbc:postgresql://localhost:4444/student
spring.datasource.username=studentcode
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect