spring.application.name=student-spring-boot
spring.datasource.url=jdbc:postgresql://localhost:4444/student
spring.datasource.username=studentcode
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
application.security.jwt.secret-key=d3c17d43de4dd1ce3446177115621704bcd0a0c74c84cab70e64b8f32884b4da
application.security.jwt.expiration=86400000